version: '3'
services:
  db:
    image: postgres:16.0-alpine
    build:
      context: docker/postgresql
    environment:
      POSTGRES_DB: db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - localnet

  web:
    build: .
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    environment:
      DATABASE_USERNAME: user
      DATABASE_PASSWORD: password
      DATABASE_HOST: db
      DATABASE_NAME: db
      DATABASE_PORT: 5432
      RAILS_ENV: development
    volumes:
      - "code:/rails"
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - localnet
  
volumes:
  postgres_data: {}
  code:
    driver: local  

networks:
  localnet:
    driver: bridge

x-mutagen:
  sync:
    defaults:
      ignore:
        vcs: true
        paths:
          - "log"
    code:
      alpha: "./"
      beta: "volume://code"
      mode: "two-way-resolved"
